version: '3.7'
services:
  
  clamav-app:
    image: tiredofit/clamav
    container_name: clamav-app
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - ZABBIX_HOSTNAME=clamav-app
      - DEFINITIONS_UPDATE_FREQUENCY=60
      - DEBUG_MODE=TRUE
      - EXCLUDE_PUA=Win,Packed
    networks:
      - services
    restart: always

networks:
  services:
    external: true

